### ISSUE TITLE
Issue: the app doesn't work when fields is missing on the wire call

### ISSUE THREAD

**Issue by forcetrekker** [JodieM/Indicators#19]
Nice application, to see the demo I installed it on my DEV org, didn't work properly as without any modifications I was unable to see anything on the UI.

After adding fields property to wire, this seems to be working and I get one icon on the UI. For now to test just hardcoded the Opportunity.Name
`@wire(getRecord, { recordId: '$recordId', fields: ['Opportunity.Name'], optionalfields: '$apiFieldnameDefinitions' })`

**Comment by JodieM** [comment]
Did you use the deploy button? I will try to work out what is going on with it. Yeah. The documentation says one field is required but it has worked without it.

**Comment by forcetrekker** [comment]
I see, In my case I just downloaded the LWC components and added them to my force-app folder on my dev org and deployed them.

**Comment by JodieM** [comment]
Thanks for that pickup @forcetrekker, that is fixed now.
